# Generated by Django 5.1.3 on 2024-12-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysticapp', '0003_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
